### ISSUE TITLE
Separators replacement

### ISSUE THREAD

**Issue by gandaldf** [tectil/NCommand#1]
Hi! Could be possible to setup which separators to use?
For example if I'd like to use something like: myapp.exe cmd1 -par=var1... Where "-" replaces the default "/" and "=" replaces the default ":" 
Do you think it could be added as a feature?

**Comment by tectil** [comment]
Other command patterns are planned. I'll publish a new version in the coming days.

**Comment by gandaldf** [comment]
Ok! Thank you very much!

**Comment by tectil** [comment]
I just released a new package. To use myapp.exe cmd1 -par=var1 style command setup your console as following:

NCommands commands = new NCommands();
commands.Context.Configuration.Notation = ParserNotation.Unix;
commands.RunConsole(args);

**Comment by gandaldf** [comment]
Thank you very much!
I will test it in the next days!
